name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Créer et activer l'environnement virtuel
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      - name: Installer les dépendances
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest scikit-learn pandas numpy matplotlib seaborn

      - name: Exécuter les tests
        run: |
          source .venv/bin/activate
          pytest -v
